apiVersion: v1
kind: Service
metadata:
  name: <APPNAME>
  namespace: <NAMESPACE>
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: <APPNAME>
  type: ClusterIP
